# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import function_pb2 as function__pb2


class FunctionStub(object):
  """The function server definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Invoke = channel.unary_unary(
        '/baetyl.Function/Invoke',
        request_serializer=function__pb2.MessageRequest.SerializeToString,
        response_deserializer=function__pb2.MessageRequest.FromString,
        )


class FunctionServicer(object):
  """The function server definition.
  """

  def Invoke(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FunctionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Invoke': grpc.unary_unary_rpc_method_handler(
          servicer.Invoke,
          request_deserializer=function__pb2.MessageRequest.FromString,
          response_serializer=function__pb2.MessageRequest.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'baetyl.Function', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
